config/routes.rb
SdharRailswolf::Application.routes.draw do
  root 'static_pages#home'

  resources :users do
    resource :character, except: [:new, :create, :destroy, :edit, :update] do
      member do
        post 'move' 
        post 'kill'
        post 'vote' 
        get  'show_alive' 
      end
    end
    post 'reg_id' 
  end

  resources :events, only: [:index]

  resources :sessions, only: [:new, :create, :destroy] 
  resource :game, only: [:new, :reset]

  match '/signup',      to: 'users#new',            via: 'get'
  match '/signin',      to: 'sessions#new',         via: 'get'
  match '/signout',     to: 'sessions#destroy',     via: 'delete'
  match '/help',        to: 'static_pages#help',    via: 'get'
  match '/about',       to: 'static_pages#about',   via: 'get'
  match '/contact',     to: 'static_pages#contact', via: 'get'

  

end

app/models/game.rb
class Game < ActiveRecord::Base

  def self.update_game
    puts "Starting game update..." 
    puts "Finding characters" 
    characters = Character.where(:dead => false).load

    puts "Finding game" 
    game = Game.find_by_id(1) 

    puts "Checking game activity"
    if game and game.active 
      charactervotes = Character.where(:dead => false).load
      charactervotes.each do |char| 
        char.voted = false
        char.save
      end

      puts "Game is active. Updating.." 

      time = Time.now 

      if time.hour%2 == 0 
        game.night = true ## Used to be day, now it's night. 
        charToKill = characters.order(:votes).last
        puts "Character to kill: " + charToKill.user.name


        ## Add event to record 
        event = Event.new 
        event.victim = charToKill.user.name
        event.killer = "Townspeople" 
        event.latitude = charToKill.latitude 
        event.longitude= charToKill.longitude
        event.event_type = "execute" 
        event.save 

        charToKill.dead = true
        charToKill.save

        if !charToKill.user.registration_id.blank?
          n = Rapns::Gcm::Notification.new 
          n.app = Rapns::Gcm::App.find_by_name("droidwolf") 
          n.data = {:message => "You have been executed by popular vote! Better luck next time."} 
          n.registration_ids = charToKill.user.registration_id
          n.save! 
          Rapns.push
        end

        ## Reset all votes and assign points
        ## Reload characters because one died 

        characters = Character.where(:dead => false).load 
        characters.each do |char|
          puts "Resetting votes for " + char.user.name
          char.votes = 0
          char.score += 100
          char.save 
        end

        game.num_alive = game.num_alive-1

        if charToKill.werewolf
          game.num_were = game.num_were-1
        else
          game.num_town = game.num_town-1
        end

        if game.num_were == 0
          finish
        elsif game.num_town == 0
          finish
        elsif game.num_alive == 0
          finish
        end
      else 
        characters = Character.where(:dead => false).load
        characters.each do |char| 
          puts "Adding score to " + char.user.name
          char.score += 100 
          char.save 
        end
        game.night = false
      end

    puts "Saving game..." 
    game.save
    end
  end

  def self.finish
    game = Game.find(1) 
    characters = Character.where(:dead => false).load 

    ## Add points for being alive at the end of the game
    characters.each do |char| 
      char.score += 1000
      char.save
    end

    ## Load all characters regardless of whether or not they're dead and reset
    #highscore and stuff. 
    characters = Character.load
    characters.each do |char| 
      if char.max_score < char.score 
        char.max_score = char.score
        char.save
      end
    end

    puts "Game is over!" 
    if game.num_were == 0
      puts "Townspeople won!"
    elsif game.num_town == 0
      puts "Werewolves won!" 
    end
    game.active = false 
    game.save 
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :admin_user,     only: [:create, :destroy] 

  def new 
    game = Game.find_by_id(1)

    if !game 
      Event.delete_all
      event = Event.new 
      event.event_type = "start" 
      event.save 
      
      characters = Character.all

      characters.each do |char| 
        if char.max_score < char.score 
          char.max_score = char.score
        end

        char.score = 0
        char.dead = false
        char.save
      end

      game = Game.new
      game.active = true 
      game.night = true 
      game.num_alive = Character.where(:dead => false).all.count

      characters = Character.all 
      characters = characters.shuffle!

      numWerewolves = characters.count/4

      game.num_were = numWerewolves
      game.num_town = game.num_alive - game.num_were

      (0..numWerewolves).each do |i|
        character = characters[i]
        character.werewolf = true
      end


      if game.save
        puts "Game created with id = " + game.id.to_s
        flash[:success] = "Game created with id = " + game.id.to_s
        render 'manage' 
      else 
        puts "Error creating game!" 
        flash[:error] = "Error creating game!" 
      end
    end
  end

  def reset
    Game.delete_all
    new 
  end

  def show
    render 'manage' 
  end 


  def finish
    game = Game.find(1) 
    game.active = false
  end

  def index
    @kills = Kill.paginate(page: params[:page])
    respond_with @kills
  end

  private
    def admin_user
      if !current_user.admin? 
        redirect_to(root_url) 
      end
    end
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/index.html.erb
<% provide(:title, 'Game Overview') %>
<h1>Game Overview</h1> 

<% if current_user.admin? %> 
  <div class='center hero-unit'> 
    <%= link_to "Create game!", new_game_path, class: "btn btn-large btn-primary" %>
    <%= link_to "Administer game!", edit_game_path, class: "btn btn-large btn-primary" %>
  </div> 
<% end %>

<div class='container-fluid'> 
  <div class='row-fluid'> 
    <div class='span4'> 
      <ul class='kills'> 
        <%= render @kills %>
      </ul> 
    </div> 

    <div class='span8' id='map'> 
    </div> 
  </div>
</div> 


<script> 
var defaulticon = L.icon({

    iconUrl:   '<%= asset_path('marker-icon.png') %>',
    shadowUrl: '<%= asset_path('marker-shadow.png') %>',

    //iconSize:     [38, 95], // size of the icon
    //shadowSize:   [50, 64], // size of the shadow
    iconAnchor:   [0, 32], // point of the icon which will correspond to marker's location
    //shadowAnchor: [4, 62],  // the same for the shadow
    popupAnchor:  [6, -32] // point from which the popup should open relative to the iconAnchor
});
  var lat = 37.2707;  
  var lon = -76.7120; 

  var map = L.map('map', {
      center: [lat, lon],
      zoom: 15
  });

  L.tileLayer('http://{s}.tile.cloudmade.com/{key}/{styleId}/256/{z}/{x}/{y}.png', {
    key: '0b9e3b46e10f417182b04a610be00f88',
    styleId: 997
  }).addTo(map);



<% @kills.each do |k| %> 
  var popupText = "<%= k.victim %> died here :(";
  lat = <%= k.latitude %>
  lon = <%= k.longitude %>
  L.marker([lat, lon], {icon: defaulticon}).bindPopup(popupText).openPopup().addTo(map);
  
<% end %>
</script>

app/views/games/manage.html.erb
<% provide(:title, 'Create Game') %>
<h1>Create Game</h1>

<div class="center hero-unit">
<%= link_to "Create game!", new_game_path, class: "btn btn-large btn-primary" %> 

</div> 